# Generated by Django 5.0.7 on 2024-12-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_remove_customuser_cpf_remove_customuser_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
